/**
 * Seed продукти за магазина — типични FiveM стоки.
 * Използват се като резерв при празна база или за един път insert в Supabase.
 */
export type SeedProduct = {
  slug: string;
  name: string;
  subtitle: string;
  price: string;
  original_price: string;
  description: string;
  long_description: string;
  includes: string[];
  badge: string | null;
  category: "vip" | "cars" | "businesses" | "gang" | "other";
  image_url: string | null;
  sort_order: number;
  is_active: boolean;
  stripe_price: string | null;
};

export const shopSeedProducts: SeedProduct[] = [
  // ─── VIP ───
  {
    slug: "vip-bronze",
    name: "VIP Bronze",
    subtitle: "Входно ниво привилегии",
    price: "4.99",
    original_price: "9.99",
    description: "Основен VIP пакет за по-добро изживяване в сървъра.",
    long_description: "VIP Bronze дава достъп до приоритетна поддръжка, специални емоджита в Discord и малки предимства в играта. Подходящ за тези, които искат да подкрепят сървъра.",
    includes: ["Приоритет в опашката", "Discord роля VIP Bronze", "10% отстъпка в магазина"],
    badge: "Популярно",
    category: "vip",
    image_url: null,
    sort_order: 1,
    is_active: true,
    stripe_price: null,
  },
  {
    slug: "vip-silver",
    name: "VIP Silver",
    subtitle: "Средни привилегии",
    price: "11.99",
    original_price: "23.99",
    description: "Разширен VIP с допълнителни възможности.",
    long_description: "VIP Silver включва всичко от Bronze плюс ексклузивни превозни средства за спавън, допълнителни слотове за инвентар и специални титли в чата.",
    includes: ["Всичко от Bronze", "Спавън на личен автомобил", "+2 слота инвентар", "Специална титла в чат"],
    badge: null,
    category: "vip",
    image_url: null,
    sort_order: 2,
    is_active: true,
    stripe_price: null,
  },
  {
    slug: "vip-gold",
    name: "VIP Gold",
    subtitle: "Пълен VIP пакет",
    price: "29.99",
    original_price: "59.99",
    description: "Максимални привилегии за сериозни играчи.",
    long_description: "VIP Gold е най-високият VIP ранг. Включва всички предимства, личен гараж с 3 спавъна, приоритет при събития и ексклузивни предмети.",
    includes: ["Всичко от Silver", "Личен гараж (3 коли)", "Приоритет при събития", "Ексклузивни кожени и аксесоари"],
    badge: "Най-добра стойност",
    category: "vip",
    image_url: null,
    sort_order: 3,
    is_active: true,
    stripe_price: null,
  },
  // ─── Коли ───
  {
    slug: "starter-car-pack",
    name: "Custom Car",
    subtitle: "Персонализирана кола по избор",
    price: "7.99",
    original_price: "14.99",
    description: "Пакет от 3 превозни средства за начало на играта.",
    long_description: "Получи веднага три превозни средства: седан за всекидневие, джип за терен и спортна кола за забавление. Всички са регистрирани на твоя персонаж.",
    includes: ["Седан (напр. Sultan)", "SUV/джип", "Спортна кола"],
    badge: null,
    category: "cars",
    image_url: null,
    sort_order: 10,
    is_active: true,
    stripe_price: null,
  },
  {
    slug: "super-car-single",
    name: "Super Custom Car",
    subtitle: "Избор от списък",
    price: "15",
    original_price: "29.99",
    description: "Една супер кола по твой избор от списъка.",
    long_description: "Избери една супер кола от одобрения списък (напр. T20, Zentorno, Nero). Колата се добавя в гаражния ти слот и е за постоянно.",
    includes: ["1 супер кола по избор", "Гаражен слот", "Регистрация"],
    badge: null,
    category: "cars",
    image_url: null,
    sort_order: 11,
    is_active: true,
    stripe_price: null,
  },
  {
    slug: "super-car-pack-3",
    name: "Off Road Car",
    subtitle: "Джип / офроуд по избор",
    price: "9.74",
    original_price: "18.74",
    description: "Едно офроуд превозно средство по твой избор.",
    long_description: "Избери един джип или офроуд автомобил от списъка. Подходящ за терен и град.",
    includes: ["1 офроуд/джип по избор", "Гаражен слот", "Регистрация"],
    badge: "Отстъпка",
    category: "cars",
    image_url: null,
    sort_order: 12,
    is_active: true,
    stripe_price: null,
  },
  {
    slug: "motorcycle-pack",
    name: "Motorcycle",
    subtitle: "2 мотора",
    price: "4.49",
    original_price: "8.99",
    description: "Два мотора за бързо придвижване.",
    long_description: "Пакет от два мотора — спортнен и круизер или по избор от списъка. Идеално за bike roleplay и бързо придвижване в града.",
    includes: ["Спортен мотоциклет", "Втори мотоциклет по избор"],
    badge: null,
    category: "cars",
    image_url: null,
    sort_order: 13,
    is_active: true,
    stripe_price: null,
  },
  {
    slug: "heli-spawn",
    name: "Helicopter",
    subtitle: "Личен хеликоптер",
    price: "60",
    original_price: "120",
    description: "Достъп до спавън на личен хеликоптер.",
    long_description: "Получи право да спавваш личен хеликоптер (по избор от списъка). Подходящ за бизнес, бързи преходи и RP.",
    includes: ["Хеликоптер по избор", "Спавън право", "Гаражен слот"],
    badge: null,
    category: "cars",
    image_url: null,
    sort_order: 14,
    is_active: true,
    stripe_price: null,
  },
  {
    slug: "boat-pack",
    name: "Boat",
    subtitle: "Лодка + джет",
    price: "6.74",
    original_price: "13.49",
    description: "Пакет за водни превозни средства.",
    long_description: "Лодка и воден скутер/джет за пристанището и морето. Идеално за риболов и морски RP.",
    includes: ["Лодка", "Воден скутер/джет", "Пристанищен слот"],
    badge: null,
    category: "cars",
    image_url: null,
    sort_order: 15,
    is_active: true,
    stripe_price: null,
  },
  // ─── Бизнеси ───
  {
    slug: "business-small",
    name: "Малък бизнес",
    subtitle: "Собственост на сграда",
    price: "12.50",
    original_price: "24.99",
    description: "Базова собственост на малък бизнес (магазин, бар, сервиз).",
    long_description: "Получи собственост върху малък бизнес по споразумение със стафа. Включва интерьер, име и възможност за печалба от играчи.",
    includes: ["Собственост на сграда", "Интерьер", "Име и регистрация", "Базова печалба"],
    badge: null,
    category: "businesses",
    image_url: null,
    sort_order: 20,
    is_active: true,
    stripe_price: null,
  },
  {
    slug: "business-medium",
    name: "Голям Бизнес",
    subtitle: "По-голям обект",
    price: "24.99",
    original_price: "49.99",
    description: "Голям бизнес с повече възможности.",
    long_description: "Голям бизнес (ресторант, клуб, автосервиз с повече слотове). Повече печалба и възможности за наемане на персонал.",
    includes: ["Всичко от малък бизнес", "По-голям обект", "Повече печалба", "Възможност за наемане"],
    badge: null,
    category: "businesses",
    image_url: null,
    sort_order: 21,
    is_active: true,
    stripe_price: null,
  },
  {
    slug: "dealership-slot",
    name: "Автосервиз",
    subtitle: "Ремонт и обслужване",
    price: "24.99",
    original_price: "49.99",
    description: "Един слот за автосервиз – ремонт и обслужване на превозни средства.",
    long_description: "Право да работиш като автосервиз: ремонти, поддръжка и обслужване на коли. Подходящ за играчи, които искат да са механици.",
    includes: ["Слот за автосервиз", "Право на ремонт и обслужване", "Договор с управлението"],
    badge: "Ексклузив",
    category: "businesses",
    image_url: null,
    sort_order: 23,
    is_active: true,
    stripe_price: null,
  },
  // ─── Генг ───
  {
    slug: "gang-slot",
    name: "Генг слот",
    subtitle: "1 слот за член",
    price: "8.13",
    original_price: "16.25",
    description: "Един слот за член в бандата.",
    long_description: "Допълнителен слот за член в официално регистрирана банда. Позволява да добавиш още един играч в бандата.",
    includes: ["1 слот за член", "Достъп до бандата"],
    badge: null,
    category: "gang",
    image_url: null,
    sort_order: 30,
    is_active: true,
    stripe_price: null,
  },
  {
    slug: "gang-car",
    name: "Генг кола",
    subtitle: "Кола на бандата",
    price: "7.50",
    original_price: "14.99",
    description: "Един слот за превозно средство на бандата.",
    long_description: "Право на бандата да притежава още едно превозно средство – генг кола, достъпна за всички членове.",
    includes: ["Слот за банда кола", "Достъп за членовете"],
    badge: null,
    category: "gang",
    image_url: null,
    sort_order: 31,
    is_active: true,
    stripe_price: null,
  },
  {
    slug: "gang-garage",
    name: "Генг Гараж",
    subtitle: "Гараж за бандата",
    price: "12.50",
    original_price: "24.99",
    description: "Гараж за превозни средства на бандата.",
    long_description: "Собствен гараж за бандата – паркиране и съхранение на генг коли. По-голям капацитет и сигурност.",
    includes: ["Гараж за бандата", "Паркиране на коли", "Достъп за членовете"],
    badge: null,
    category: "gang",
    image_url: null,
    sort_order: 32,
    is_active: true,
    stripe_price: null,
  },
  {
    slug: "gang-vault",
    name: "Генг Хазна",
    subtitle: "Хазна за бандата",
    price: "14.99",
    original_price: "29.99",
    description: "Хазна за съхранение на пари и стоки на бандата.",
    long_description: "Официална хазна на бандата – съхранение на общи пари, наркотици или други стоки. Достъп по нива за членовете.",
    includes: ["Хазна за бандата", "Съхранение на пари/стоки", "Контрол на достъпа"],
    badge: null,
    category: "gang",
    image_url: null,
    sort_order: 33,
    is_active: true,
    stripe_price: null,
  },
  {
    slug: "gang-stash",
    name: "Генг Сташ",
    subtitle: "Склад/сташ за бандата",
    price: "15",
    original_price: "30",
    description: "Сташ (склад) за оръжия и стоки на бандата.",
    long_description: "Собствен сташ на бандата – склад за оръжия, боеприпаси и стоки. По-голям капацитет от базовия инвентар.",
    includes: ["Сташ за бандата", "Склад за оръжия и стоки", "Достъп за членовете"],
    badge: null,
    category: "gang",
    image_url: null,
    sort_order: 34,
    is_active: true,
    stripe_price: null,
  },
  // ─── Други ───
  {
    slug: "safe-house",
    name: "Сейф House",
    subtitle: "Сейф за жилище",
    price: "12.99",
    original_price: "17.99",
    description: "Сейф за съхранение в жилище/къща.",
    long_description: "Собствен сейф в жилището ти – съхранение на пари, документи и ценности. Достъпен само за теб или за хора с ключ.",
    includes: ["Сейф в жилище", "Съхранение на пари/ценности", "Защита от кражба"],
    badge: null,
    category: "gang",
    image_url: null,
    sort_order: 35,
    is_active: true,
    stripe_price: null,
  },
  {
    slug: "custom-plate",
    name: "Custom Номер",
    subtitle: "Собствен номер",
    price: "2.99",
    original_price: "5.99",
    description: "Една персонализирана регистрация за МПС.",
    long_description: "Избери свой текст за регистрационен номер (в рамките на правилата). Валидна за едно превозно средство.",
    includes: ["Персонализиран номер", "Приложима за 1 МПС"],
    badge: null,
    category: "other",
    image_url: null,
    sort_order: 40,
    is_active: true,
    stripe_price: null,
  },
  {
    slug: "villa",
    name: "Вила",
    subtitle: "Жилище / имот",
    price: "6",
    original_price: "12",
    description: "Собствена вила за живеене в сървъра.",
    long_description: "Получи собствена вила – жилище с интерьер, гараж и възможност за персонализация. Договор със стафа за местоположение и детайли.",
    includes: ["Собствена вила", "Интерьер", "Договор със стафа"],
    badge: null,
    category: "other",
    image_url: null,
    sort_order: 41,
    is_active: true,
    stripe_price: null,
  },
  {
    slug: "donation-large",
    name: "Дарение — голямо",
    subtitle: "Подкрепи сървъра",
    price: "19.99",
    original_price: "24.99",
    description: "Голямо дарение за подкрепа на сървъра.",
    long_description: "Подкрепи ChillRP с по-голямо дарение. Средствата помагат за поддръжка и развитие на сървъра. Благодарим ви!",
    includes: ["Дарение за сървъра", "Благодарност от екипа"],
    badge: null,
    category: "other",
    image_url: null,
    sort_order: 45,
    is_active: true,
    stripe_price: null,
  },
  {
    slug: "donation-small",
    name: "Дарение — малко",
    subtitle: "Подкрепи сървъра",
    price: "2.99",
    original_price: "2.99",
    description: "Малко дарение за поддръжка на сървъра.",
    long_description: "Доброволно дарение. Част от средствата отиват за сървър и разработка. Може да получиш малък благодарствен предмет в играта.",
    includes: ["Благодарност от екипа", "Възможен малък подарък в игра"],
    badge: "Дарение",
    category: "other",
    image_url: null,
    sort_order: 43,
    is_active: true,
    stripe_price: null,
  },
  {
    slug: "donation-medium",
    name: "Дарение — средно",
    subtitle: "Подкрепи сървъра",
    price: "9.99",
    original_price: "9.99",
    description: "Средно дарение за поддръжка на сървъра.",
    long_description: "Доброволно дарение. Подкрепяш развитието на ChillRP. Може да получиш специална благодарност в Discord и малък предмет в играта.",
    includes: ["Благодарност в Discord", "Възможен подарък в игра"],
    badge: "Дарение",
    category: "other",
    image_url: null,
    sort_order: 44,
    is_active: true,
    stripe_price: null,
  },
  {
    slug: "priority-queue",
    name: "Приоритетна опашка",
    subtitle: "30 дни",
    price: "1.25",
    original_price: "2.50",
    description: "Приоритет при влизане в сървъра за 30 дни.",
    long_description: "Влизай по-бързо в пълния сървър — приоритетна опашка за 30 дни. Не включва VIP предимства.",
    includes: ["Приоритет в опашката — 30 дни"],
    badge: null,
    category: "other",
    image_url: null,
    sort_order: 42,
    is_active: true,
    stripe_price: null,
  },
];
