// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { getSupabaseSiteUrl } from "@/lib/supabaseSiteUrl";

const resolvedSupabaseUrl = getSupabaseSiteUrl();
const SUPABASE_URL = resolvedSupabaseUrl || "https://configure-vite-supabase-url.invalid";
if (!resolvedSupabaseUrl && import.meta.env.DEV) {
  console.warn(
    "[Supabase] Задай VITE_SUPABASE_URL (и anon key) в .env за новия проект — виж .env.example.",
  );
} else if (!resolvedSupabaseUrl && import.meta.env.PROD) {
  console.error(
    "[Supabase] Липсва валиден VITE_SUPABASE_URL в билда. Попълни .env и пусни отново npm run build (Vite вгражда променливите при build).",
  );
}
const anonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_ANON_KEY = anonKey && anonKey.length > 20 ? anonKey : "missing-anon-key";
if (import.meta.env.DEV && (!anonKey || anonKey.length < 20)) {
  console.warn(
    "[Supabase] Липсва VITE_SUPABASE_ANON_KEY (или legacy VITE_SUPABASE_PUBLISHABLE_KEY) в .env — от Dashboard → Settings → API.",
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // PKCE exchange runs once inside the client’s _initialize(); do not also call exchangeCodeForSession
    // in the app or the code verifier is already gone → AuthPKCECodeVerifierMissingError.
    detectSessionInUrl: true,
    flowType: "pkce",
  },
});