// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const CORRECT_SUPABASE_URL = "https://zbvqakalrxaxkwbpmjhn.supabase.co";
const rawUrl = import.meta.env.VITE_SUPABASE_URL || CORRECT_SUPABASE_URL;
const SUPABASE_URL = rawUrl.includes("zbvqakalrxaxkwbpmjhn") ? rawUrl : CORRECT_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "missing-publishable-key";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});